accounts:
  - name: Assets:Default
    address: "<YOUR_ETHEREUM_ACCOUNT>"
defaultExpense: Expenses:Default
defaultIncome: Income:Default
pnlAccount: Income:Pnl
txFeeAccount: Expenses:Ethereum:TxFee
baseCurrency: USD
etherscan:
  apiKey: "<YOUR_ETHERSCAN_API_KEY>"
